"""add_workers_table

Revision ID: 05d50775a665
Revises: 75efe7bbc4cd
Create Date: 2026-01-08 15:06:52.723248

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05d50775a665'
down_revision: Union[str, Sequence[str], None] = '75efe7bbc4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_workspace_id'), 'workers', ['workspace_id'], unique=False)
    op.add_column('cron_tasks', sa.Column('worker_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cron_tasks_worker_id'), 'cron_tasks', ['worker_id'], unique=False)
    op.create_foreign_key(None, 'cron_tasks', 'workers', ['worker_id'], ['id'], ondelete='SET NULL')
    op.add_column('delayed_tasks', sa.Column('worker_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_delayed_tasks_worker_id'), 'delayed_tasks', ['worker_id'], unique=False)
    op.create_foreign_key(None, 'delayed_tasks', 'workers', ['worker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delayed_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_delayed_tasks_worker_id'), table_name='delayed_tasks')
    op.drop_column('delayed_tasks', 'worker_id')
    op.drop_constraint(None, 'cron_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_cron_tasks_worker_id'), table_name='cron_tasks')
    op.drop_column('cron_tasks', 'worker_id')
    op.drop_index(op.f('ix_workers_workspace_id'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
