"""Add notification_templates table

Revision ID: 1b4363cc1e2c
Revises: a1b2c3d4e5f6
Create Date: 2026-01-09 11:38:06.033670

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b4363cc1e2c"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_templates",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("channel", sa.Enum("EMAIL", "TELEGRAM", name="notificationchannel"), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("variables", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "language", "channel", name="uq_template_code_lang_channel"),
    )
    op.create_index(op.f("ix_notification_templates_channel"), "notification_templates", ["channel"], unique=False)
    op.create_index(op.f("ix_notification_templates_code"), "notification_templates", ["code"], unique=False)
    op.create_index(op.f("ix_notification_templates_language"), "notification_templates", ["language"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_templates_language"), table_name="notification_templates")
    op.drop_index(op.f("ix_notification_templates_code"), table_name="notification_templates")
    op.drop_index(op.f("ix_notification_templates_channel"), table_name="notification_templates")
    op.drop_table("notification_templates")
    # ### end Alembic commands ###
