"""Initial migration

Revision ID: f645c1f88fb9
Revises:
Create Date: 2026-01-08 00:50:54.769709

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f645c1f88fb9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_monthly", sa.Integer(), nullable=False),
        sa.Column("price_yearly", sa.Integer(), nullable=False),
        sa.Column("max_cron_tasks", sa.Integer(), nullable=False),
        sa.Column("max_delayed_tasks_per_month", sa.Integer(), nullable=False),
        sa.Column("max_workspaces", sa.Integer(), nullable=False),
        sa.Column("max_execution_history_days", sa.Integer(), nullable=False),
        sa.Column("min_cron_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("telegram_notifications", sa.Boolean(), nullable=False),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("webhook_callbacks", sa.Boolean(), nullable=False),
        sa.Column("custom_headers", sa.Boolean(), nullable=False),
        sa.Column("retry_on_failure", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_username", sa.String(length=255), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("cron_tasks_count", sa.Integer(), nullable=False),
        sa.Column("delayed_tasks_this_month", sa.Integer(), nullable=False),
        sa.Column("default_timezone", sa.String(length=50), nullable=False),
        sa.Column("webhook_secret", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_owner_id"), "workspaces", ["owner_id"], unique=False)
    op.create_index(op.f("ix_workspaces_plan_id"), "workspaces", ["plan_id"], unique=False)
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "cron_tasks",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "method", sa.Enum("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", name="httpmethod"), nullable=False
        ),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("schedule", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("retry_delay_seconds", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column(
            "last_status",
            sa.Enum("PENDING", "RUNNING", "SUCCESS", "FAILED", "CANCELLED", name="taskstatus"),
            nullable=True,
        ),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("notify_on_failure", sa.Boolean(), nullable=False),
        sa.Column("notify_on_recovery", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cron_tasks_is_active"), "cron_tasks", ["is_active"], unique=False)
    op.create_index(op.f("ix_cron_tasks_next_run_at"), "cron_tasks", ["next_run_at"], unique=False)
    op.create_index(op.f("ix_cron_tasks_workspace_id"), "cron_tasks", ["workspace_id"], unique=False)
    op.create_table(
        "delayed_tasks",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "method", sa.Enum("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", name="httpmethod"), nullable=False
        ),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("execute_at", sa.DateTime(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("retry_delay_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("PENDING", "RUNNING", "SUCCESS", "FAILED", "CANCELLED", name="taskstatus"), nullable=False
        ),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("retry_attempt", sa.Integer(), nullable=False),
        sa.Column("callback_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "idempotency_key", name="uq_delayed_idempotency"),
    )
    op.create_index(op.f("ix_delayed_tasks_execute_at"), "delayed_tasks", ["execute_at"], unique=False)
    op.create_index(op.f("ix_delayed_tasks_idempotency_key"), "delayed_tasks", ["idempotency_key"], unique=False)
    op.create_index(op.f("ix_delayed_tasks_status"), "delayed_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_delayed_tasks_workspace_id"), "delayed_tasks", ["workspace_id"], unique=False)
    op.create_table(
        "notification_settings",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("telegram_enabled", sa.Boolean(), nullable=False),
        sa.Column("telegram_chat_ids", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_addresses", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("webhook_enabled", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=2048), nullable=True),
        sa.Column("webhook_secret", sa.String(length=255), nullable=True),
        sa.Column("notify_on_failure", sa.Boolean(), nullable=False),
        sa.Column("notify_on_recovery", sa.Boolean(), nullable=False),
        sa.Column("notify_on_success", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_settings_workspace_id"), "notification_settings", ["workspace_id"], unique=True
    )
    op.create_table(
        "payments",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "WAITING_FOR_CAPTURE", "SUCCEEDED", "CANCELLED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("yookassa_payment_id", sa.String(length=255), nullable=True),
        sa.Column("yookassa_confirmation_url", sa.String(length=2048), nullable=True),
        sa.Column("yookassa_payment_method", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("yookassa_payment_id"),
    )
    op.create_index(op.f("ix_payments_workspace_id"), "payments", ["workspace_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "PAST_DUE", "CANCELLED", "EXPIRED", name="subscriptionstatus"), nullable=False
        ),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("yookassa_payment_method_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_plan_id"), "subscriptions", ["plan_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_workspace_id"), "subscriptions", ["workspace_id"], unique=True)
    op.create_table(
        "executions",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=True),
        sa.Column("cron_task_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.Enum("PENDING", "RUNNING", "SUCCESS", "FAILED", "CANCELLED", name="taskstatus"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("retry_attempt", sa.Integer(), nullable=False),
        sa.Column("request_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "request_method",
            sa.Enum("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", name="httpmethod"),
            nullable=False,
        ),
        sa.Column("request_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column("response_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("response_size_bytes", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["cron_task_id"], ["cron_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_executions_task_id"), "executions", ["task_id"], unique=False)
    op.create_index(op.f("ix_executions_workspace_id"), "executions", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_executions_workspace_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_task_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_subscriptions_workspace_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_plan_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_payments_workspace_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_notification_settings_workspace_id"), table_name="notification_settings")
    op.drop_table("notification_settings")
    op.drop_index(op.f("ix_delayed_tasks_workspace_id"), table_name="delayed_tasks")
    op.drop_index(op.f("ix_delayed_tasks_status"), table_name="delayed_tasks")
    op.drop_index(op.f("ix_delayed_tasks_idempotency_key"), table_name="delayed_tasks")
    op.drop_index(op.f("ix_delayed_tasks_execute_at"), table_name="delayed_tasks")
    op.drop_table("delayed_tasks")
    op.drop_index(op.f("ix_cron_tasks_workspace_id"), table_name="cron_tasks")
    op.drop_index(op.f("ix_cron_tasks_next_run_at"), table_name="cron_tasks")
    op.drop_index(op.f("ix_cron_tasks_is_active"), table_name="cron_tasks")
    op.drop_table("cron_tasks")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_plan_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_owner_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("plans")
    # ### end Alembic commands ###
