import React, { ReactElement } from 'react'
import { render, RenderOptions } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { I18nextProvider } from 'react-i18next'
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Initialize a test i18n instance
const testI18n = i18n.createInstance()
testI18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  resources: {
    en: {
      translation: {
        // Common
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.create': 'Create',
        'common.loading': 'Loading...',
        'common.error': 'Error',
        'common.success': 'Success',
        'common.saveChanges': 'Save Changes',
        // Auth
        'auth.login': 'Sign In',
        'auth.register': 'Sign Up',
        'auth.logout': 'Sign Out',
        'auth.email': 'Email',
        'auth.password': 'Password',
        'auth.name': 'Name',
        'auth.signIn': 'Sign In',
        'auth.signUp': 'Sign Up',
        'auth.signingIn': 'Signing in...',
        'auth.creatingAccount': 'Creating account...',
        'auth.createAccount': 'Create Account',
        'auth.welcomeBack': 'Welcome Back',
        'auth.enterCredentials': 'Enter your credentials to sign in',
        'auth.enterDetails': 'Enter your details to create an account',
        'auth.dontHaveAccount': "Don't have an account?",
        'auth.alreadyHaveAccount': 'Already have an account?',
        'auth.confirmPassword': 'Confirm Password',
        'auth.passwordsNotMatch': 'Passwords do not match',
        'auth.passwordTooShort': 'Password must be at least 8 characters',
        // Common extended
        'common.email': 'Email',
        'common.password': 'Password',
        'common.name': 'Name',
        // Task form
        'taskForm.name': 'Name',
        'taskForm.nameOptional': 'Name (optional)',
        'taskForm.namePlaceholder': 'Enter task name',
        'taskForm.nameRequired': 'Name is required',
        'taskForm.url': 'URL',
        'taskForm.urlPlaceholder': 'https://example.com/webhook',
        'taskForm.urlRequired': 'URL is required',
        'taskForm.method': 'HTTP Method',
        'taskForm.description': 'Description',
        'taskForm.descriptionPlaceholder': 'Task description',
        'taskForm.scheduleRequired': 'Schedule is required',
        'taskForm.timezone': 'Timezone',
        'taskForm.timeoutSeconds': 'Timeout (seconds)',
        'taskForm.retryCount': 'Retry Count',
        'taskForm.headers': 'Headers',
        'taskForm.headersPlaceholder': '{"Authorization": "Bearer token"}',
        'taskForm.invalidHeadersJson': 'Invalid JSON in headers',
        'taskForm.body': 'Request Body',
        'taskForm.createTask': 'Create Task',
        'taskForm.updateTask': 'Update Task',
        'taskForm.taskCreated': 'Task created',
        'taskForm.taskCreatedDescription': 'Task "{{name}}" has been created',
        'taskForm.taskUpdated': 'Task updated',
        'taskForm.taskUpdatedDescription': 'Task "{{name}}" has been updated',
        'taskForm.failedToCreate': 'Failed to create task',
        'taskForm.failedToUpdate': 'Failed to update task',
        'taskForm.executeAt': 'Execute At',
        'taskForm.executeAtRequired': 'Execution time is required',
        'taskForm.executeAtFuture': 'Execution time must be in the future',
        'taskForm.scheduleTask': 'Schedule Task',
        'taskForm.advancedOptions': 'Advanced Options',
        'taskForm.idempotencyKey': 'Idempotency Key',
        'taskForm.idempotencyKeyHint': 'Optional unique identifier to prevent duplicate tasks',
        'taskForm.tags': 'Tags',
        'taskForm.tagsPlaceholder': 'tag1, tag2, tag3',
        'taskForm.tagsHint': 'Comma-separated list of tags',
        'taskForm.callbackUrl': 'Callback URL',
        'taskForm.callbackUrlHint': 'URL to call after task execution',
        'taskForm.in5minutes': 'In 5 minutes',
        'taskForm.in15minutes': 'In 15 minutes',
        'taskForm.in30minutes': 'In 30 minutes',
        'taskForm.in1hour': 'In 1 hour',
        'taskForm.in3hours': 'In 3 hours',
        'taskForm.in24hours': 'In 24 hours',
        // Cron builder
        'cronBuilder.label': 'Schedule (Cron)',
        'cronBuilder.builder': 'Builder',
        'cronBuilder.title': 'Schedule Builder',
        'cronBuilder.description': 'Choose a preset or build a custom schedule',
        'cronBuilder.presets': 'Presets',
        'cronBuilder.custom': 'Custom',
        'cronBuilder.advanced': 'Advanced',
        'cronBuilder.frequent': 'Frequent',
        'cronBuilder.daily': 'Daily',
        'cronBuilder.weekly': 'Weekly',
        'cronBuilder.monthly': 'Monthly',
        'cronBuilder.frequency': 'Frequency',
        'cronBuilder.everyXMinutes': 'Every X minutes',
        'cronBuilder.everyXHours': 'Every X hours',
        'cronBuilder.every': 'Every',
        'cronBuilder.minutes': 'minutes',
        'cronBuilder.hours': 'hours',
        'cronBuilder.atMinute': 'At minute',
        'cronBuilder.time': 'Time',
        'cronBuilder.days': 'Days',
        'cronBuilder.dayOfMonth': 'Day of month',
        'cronBuilder.preview': 'Preview',
        'cronBuilder.invalidExpression': 'Invalid expression',
        'cronBuilder.apply': 'Apply',
        'cronBuilder.cronExpression': 'Cron Expression',
        'cronBuilder.formatHelp': 'Format: minute hour day month weekday',
        'cronBuilder.minute': 'Minute',
        'cronBuilder.hour': 'Hour',
        'cronBuilder.day': 'Day',
        'cronBuilder.month': 'Month',
        'cronBuilder.weekday': 'Weekday',
        'cronBuilder.specialChars': 'Special characters: * (any), */n (every n), - (range), , (list)',
        'cronBuilder.sun': 'Sun',
        'cronBuilder.mon': 'Mon',
        'cronBuilder.tue': 'Tue',
        'cronBuilder.wed': 'Wed',
        'cronBuilder.thu': 'Thu',
        'cronBuilder.fri': 'Fri',
        'cronBuilder.sat': 'Sat',
        'cronBuilder.presetEveryMinute': 'Every minute',
        'cronBuilder.presetEvery5Minutes': 'Every 5 minutes',
        'cronBuilder.presetEvery10Minutes': 'Every 10 minutes',
        'cronBuilder.presetEvery15Minutes': 'Every 15 minutes',
        'cronBuilder.presetEvery30Minutes': 'Every 30 minutes',
        'cronBuilder.presetEveryHour': 'Every hour',
        'cronBuilder.presetEvery2Hours': 'Every 2 hours',
        'cronBuilder.presetEvery6Hours': 'Every 6 hours',
        'cronBuilder.presetEvery12Hours': 'Every 12 hours',
        'cronBuilder.presetDailyMidnight': 'Daily at midnight',
        'cronBuilder.presetDaily6am': 'Daily at 6 AM',
        'cronBuilder.presetDaily9am': 'Daily at 9 AM',
        'cronBuilder.presetDailyNoon': 'Daily at noon',
        'cronBuilder.presetDaily6pm': 'Daily at 6 PM',
        'cronBuilder.presetMonday9am': 'Monday at 9 AM',
        'cronBuilder.presetFriday5pm': 'Friday at 5 PM',
        'cronBuilder.presetWeekdays9am': 'Weekdays at 9 AM',
        'cronBuilder.presetWeekendsNoon': 'Weekends at noon',
        'cronBuilder.presetFirstOfMonthMidnight': 'First of month at midnight',
        'cronBuilder.presetFirstOfMonth9am': 'First of month at 9 AM',
        'cronBuilder.preset15thNoon': '15th at noon',
        'cronBuilder.presetLastDayMidnight': 'Last day of month at midnight',
        // Nav
        'nav.main': 'Main',
        'nav.settings': 'Settings',
        'nav.dashboard': 'Dashboard',
        'nav.cronTasks': 'Cron Tasks',
        'nav.delayedTasks': 'Delayed Tasks',
        'nav.executions': 'Executions',
        'nav.billing': 'Billing',
        'nav.notifications': 'Notifications',
        'nav.apiKeys': 'API Keys',
        'nav.adminDashboard': 'Admin Dashboard',
        // Header
        'header.language': 'Language',
        'header.profile': 'Profile',
        'header.logout': 'Sign Out',
        // Profile
        'profile.title': 'Profile',
        'profile.subtitle': 'Manage your profile settings',
        'profile.personalInfo': 'Personal Information',
        'profile.language': 'Language',
        'profile.languageDescription': 'Select your preferred language',
        'profile.accountInfo': 'Account Information',
        'profile.memberSince': 'Member since',
        'profile.emailVerified': 'Verified',
        'profile.emailNotVerified': 'Not verified',
        'profile.telegramNotConnected': 'Not connected',
        'profile.telegramNotConnectedDesc': 'Connect your Telegram account to receive notifications about task executions, failures, and recoveries.',
        'profile.connectTelegram': 'Connect Telegram',
        'profile.russian': 'Russian',
        'profile.english': 'English',
        'profile.saveChanges': 'Save Changes',
        'profile.saving': 'Saving...',
        // Notifications
        'notifications.settingsSaved': 'Settings saved',
        // Dashboard
        'dashboard.failedToLoad': 'Failed to load data',
        'dashboard.noWorkspacesYet': 'No workspaces yet',
        'dashboard.createFirstWorkspace': 'Create your first workspace to get started',
        'dashboard.overview': 'Overview',
        'dashboard.recentExecutions': 'Recent Executions',
        'dashboard.latestTaskExecutions': 'Latest task executions',
        'dashboard.executionsLast7Days': 'Executions Last 7 Days',
        'dashboard.successAndFailureRate': 'Success and failure rate',
        'dashboard.noExecutionDataYet': 'No execution data yet',
        'dashboard.noExecutions': 'No executions yet',
        'dashboard.activeCronTasks': 'Active Cron Tasks',
        'dashboard.pendingDelayedTasks': 'Pending Delayed Tasks',
        'dashboard.executionsToday': 'Executions Today',
        'dashboard.successRate7d': 'Success Rate (7d)',
        'dashboard.last7Days': 'Last 7 days',
        'dashboard.totalTasks': 'Total Tasks',
        'dashboard.successRate': 'Success Rate',
        'dashboard.totalExecutions': 'Total Executions',
        'dashboard.cronTasks': 'Cron Tasks',
        'dashboard.delayedTasks': 'Delayed Tasks',
        // Workspace
        'workspace.create': 'Create Workspace',
        'workspace.createNew': 'Create New Workspace',
        'workspace.createDescription': 'Create a new workspace to organize your tasks',
        'workspace.nameRequired': 'Name is required',
        'workspace.created': 'Workspace created',
        'workspace.createdDescription': 'Workspace "{{name}}" has been created',
        'workspace.name': 'Name',
        'workspace.slug': 'Slug',
        // Common status
        'common.failed': 'Failed',
        'common.running': 'Running',
        'common.pending': 'Pending',
        // Cron tasks page
        'cronTasks.title': 'Cron Tasks',
        'cronTasks.subtitle': 'Manage your scheduled recurring tasks',
        'cronTasks.createTask': 'Create Task',
        'cronTasks.noTasksYet': 'No cron tasks yet',
        'cronTasks.createFirstTask': 'Create your first cron task to get started',
        'cronTasks.errorLoading': 'Error loading tasks',
        'cronTasks.taskResumed': 'Task resumed',
        'cronTasks.taskPaused': 'Task paused',
        'cronTasks.taskDeleted': 'Task deleted',
        'cronTasks.runNow': 'Run now',
        'cronTasks.taskTriggered': 'Task triggered',
        'cronTasks.deleteConfirm': 'Are you sure you want to delete this task?',
        // Delayed tasks page
        'delayedTasks.title': 'Delayed Tasks',
        'delayedTasks.subtitle': 'Manage your scheduled one-time tasks',
        'delayedTasks.createTask': 'Schedule Task',
        'delayedTasks.noTasksYet': 'No delayed tasks yet',
        'delayedTasks.createFirstTask': 'Schedule your first task to get started',
        'delayedTasks.errorLoading': 'Error loading tasks',
        'delayedTasks.taskCancelled': 'Task cancelled',
        'delayedTasks.cancelConfirm': 'Are you sure you want to cancel this task?',
        // Executions page
        'executions.title': 'Executions',
        'executions.subtitle': 'View task execution history',
        'executions.noExecutionsYet': 'No executions yet',
        'executions.errorLoading': 'Error loading executions',
        'executions.filters': 'Filters',
        'executions.status': 'Status',
        'executions.taskType': 'Task Type',
        'executions.all': 'All',
        // Billing page
        'billing.title': 'Billing',
        'billing.subtitle': 'Manage your subscription and billing',
        'billing.currentPlan': 'Current Plan',
        'billing.paymentHistory': 'Payment History',
        'billing.noPayments': 'No payments yet',
        'billing.upgrade': 'Upgrade',
        'billing.cancel': 'Cancel Subscription',
        'billing.monthly': 'Monthly',
        'billing.yearly': 'Yearly',
        'billing.free': 'Free',
        'billing.pro': 'Pro',
        'billing.business': 'Business',
        'billing.taskChains': 'task chains',
        'billing.cronTasks': 'cron tasks',
        'billing.delayedTasksMonth': 'delayed tasks/month',
        'billing.workspaces': 'workspace',
        'billing.daysHistory': 'days history',
        'billing.minInterval': 'Min interval: {{minutes}} min',
        'billing.telegramNotifications': 'Telegram notifications',
        'billing.emailNotifications': 'Email notifications',
        'billing.webhookCallbacks': 'Webhook callbacks',
        'billing.autoRetry': 'Auto retry on failure',
        // API Keys page
        'apiKeys.title': 'API Keys',
        'apiKeys.subtitle': 'Manage your API keys',
        'apiKeys.createKey': 'Create API Key',
        'apiKeys.noKeys': 'No API keys yet',
        'apiKeys.copyKey': 'Copy',
        'apiKeys.revokeKey': 'Revoke',
        // Notifications page
        'notifications.title': 'Notifications',
        'notifications.subtitle': 'Configure notification settings',
        'notifications.email': 'Email Notifications',
        'notifications.telegram': 'Telegram Notifications',
        'notifications.webhook': 'Webhook Notifications',
        // Admin pages
        'admin.title': 'Admin Dashboard',
        'admin.subtitle': 'System administration overview',
        'admin.users': 'Users',
        'admin.usersSubtitle': 'Manage system users',
        'admin.workspaces': 'Workspaces',
        'admin.workspacesSubtitle': 'Manage workspaces',
        'admin.totalUsers': 'Total Users',
        'admin.verifiedUsers': 'Verified Users',
        'admin.activeSubscriptions': 'Active Subscriptions',
        'admin.active': 'Active',
        'admin.inactive': 'Inactive',
        'admin.verified': 'Verified',
        'admin.paidPlans': 'Paid Plans',
        'admin.tasks': 'Tasks',
        'admin.cronTasks': 'Cron Tasks',
        'admin.delayedTasks': 'Delayed Tasks',
        'admin.executionsToday': 'Executions Today',
        'admin.thisWeek': 'this week',
        'admin.successRate7d': 'Success Rate (7d)',
        'admin.totalExecutions': 'total executions',
        'admin.revenue': 'Revenue',
        'admin.revenueThisMonth': 'Revenue This Month',
        'admin.fromSubscriptions': 'From {{count}} subscriptions',
        'admin.back': 'Back',
        'admin.user': 'User',
        'admin.role': 'Role',
        'admin.admin': 'Admin',
        'admin.created': 'Created',
        'admin.editUser': 'Edit User',
        'admin.emailVerified': 'Email Verified',
        'admin.userUpdated': 'User Updated',
        'admin.userUpdatedDescription': 'User {{email}} has been updated',
        'admin.errorLoadingUsers': 'Error loading users',
        'admin.errorUpdatingUser': 'Error updating user',
        'admin.searchUsersPlaceholder': 'Search users...',
        'admin.usersTotal': '{{count}} users total',
        'admin.noUsersFound': 'No users found',
        'admin.tryDifferentSearch': 'Try a different search',
        'admin.noUsersYet': 'No users yet',
        'admin.pageOf': 'Page {{current}} of {{total}}',
        'admin.errorLoadingStats': 'Error loading stats',
        'admin.failedToLoadStats': 'Failed to load stats',
        'admin.totalWorkspaces': 'Total Workspaces',
        'admin.pending': 'pending',
        'admin.owner': 'Owner',
        'admin.plan': 'Plan',
        'admin.searchWorkspacesPlaceholder': 'Search workspaces...',
        'admin.workspacesTotal': '{{count}} workspaces total',
        'admin.noWorkspacesFound': 'No workspaces found',
        'admin.noWorkspacesYet': 'No workspaces yet',
        'admin.errorLoadingWorkspaces': 'Error loading workspaces',
        // Admin Plans
        'admin.plans.title': 'Plans',
        'admin.plans.subtitle': 'Manage subscription plans',
        'admin.plans.manage': 'Manage plans',
        'admin.plans.create': 'Create Plan',
        'admin.plans.edit': 'Edit Plan',
        'admin.plans.createDescription': 'Create a new subscription plan',
        'admin.plans.editDescription': 'Edit plan settings',
        'admin.plans.name': 'Name',
        'admin.plans.nameField': 'Name (code)',
        'admin.plans.displayName': 'Display Name',
        'admin.plans.description': 'Description',
        'admin.plans.descriptionPlaceholder': 'Plan description...',
        'admin.plans.pricing': 'Pricing',
        'admin.plans.priceMonthly': 'Monthly Price',
        'admin.plans.priceYearly': 'Yearly Price',
        'admin.plans.priceHint': 'In kopeks (100 = 1 RUB)',
        'admin.plans.limits': 'Limits',
        'admin.plans.maxCronTasks': 'Max Cron Tasks',
        'admin.plans.maxDelayedTasks': 'Max Delayed Tasks/Month',
        'admin.plans.maxWorkspaces': 'Max Workspaces',
        'admin.plans.historyDays': 'History Days',
        'admin.plans.minCronInterval': 'Min Cron Interval (min)',
        'admin.plans.sortOrder': 'Sort Order',
        'admin.plans.features': 'Features',
        'admin.plans.telegramNotifications': 'Telegram Notifications',
        'admin.plans.emailNotifications': 'Email Notifications',
        'admin.plans.webhookCallbacks': 'Webhook Callbacks',
        'admin.plans.customHeaders': 'Custom Headers',
        'admin.plans.retryOnFailure': 'Retry on Failure',
        'admin.plans.status': 'Status',
        'admin.plans.isActive': 'Active',
        'admin.plans.isPublic': 'Public',
        'admin.plans.active': 'Active',
        'admin.plans.inactive': 'Inactive',
        'admin.plans.public': 'Public',
        'admin.plans.subscriptions': 'Subscriptions',
        'admin.plans.free': 'Free',
        'admin.plans.currency': 'RUB',
        'admin.plans.month': 'month',
        'admin.plans.year': 'year',
        'admin.plans.delayedPerMonth': 'delayed/month',
        'admin.plans.minInterval': 'min interval',
        'admin.plans.noPlans': 'No plans',
        'admin.plans.noPlansDescription': 'No subscription plans have been created yet',
        'admin.plans.createFirst': 'Create First Plan',
        'admin.plans.created': 'Plan Created',
        'admin.plans.createdDescription': 'Plan has been created',
        'admin.plans.updated': 'Plan Updated',
        'admin.plans.updatedDescription': 'Plan has been updated',
        'admin.plans.deleted': 'Plan Deleted',
        'admin.plans.deletedDescription': 'Plan has been deleted',
        'admin.plans.deleteConfirm': 'Delete Plan?',
        'admin.plans.deleteWarning': 'Are you sure you want to delete {{name}}?',
        'admin.plans.errorLoading': 'Error loading plans',
        'admin.plans.errorCreating': 'Error creating plan',
        'admin.plans.errorUpdating': 'Error updating plan',
        'admin.plans.errorDeleting': 'Error deleting plan',
        // Admin Templates
        'admin.templates.title': 'Notification Templates',
        'admin.templates.subtitle': 'Manage notification templates',
        'admin.templates.manage': 'Manage templates',
        'admin.templates.edit': 'Edit Template',
        'admin.templates.code': 'Code',
        'admin.templates.language': 'Language',
        'admin.templates.channel': 'Channel',
        'admin.templates.subject': 'Subject',
        'admin.templates.subjectPlaceholder': 'Email subject...',
        'admin.templates.body': 'Body',
        'admin.templates.status': 'Status',
        'admin.templates.isActive': 'Active',
        'admin.templates.filterCode': 'Filter by code',
        'admin.templates.filterLanguage': 'Filter by language',
        'admin.templates.filterChannel': 'Filter by channel',
        'admin.templates.noTemplates': 'No templates',
        'admin.templates.noTemplatesDescription': 'No notification templates found',
        'admin.templates.preview': 'Preview',
        'admin.templates.previewTitle': 'Template Preview',
        'admin.templates.previewDescription': 'Preview with sample data',
        'admin.templates.availableVariables': 'Available Variables',
        'admin.templates.resetToDefault': 'Reset to Default',
        'admin.templates.resetConfirm': 'Reset Template?',
        'admin.templates.resetWarning': 'This will restore the default template',
        'admin.templates.updated': 'Template Updated',
        'admin.templates.updatedDescription': 'Template has been updated',
        'admin.templates.reset': 'Template Reset',
        'admin.templates.resetDescription': 'Template has been reset',
        'admin.templates.errorLoading': 'Error loading templates',
        'admin.templates.errorUpdating': 'Error updating template',
        'admin.templates.errorPreview': 'Error previewing template',
        'admin.templates.errorReset': 'Error resetting template',
        'admin.templates.codes.task_failure': 'Task Failure',
        'admin.templates.codes.task_recovery': 'Task Recovery',
        'admin.templates.codes.task_success': 'Task Success',
        'admin.templates.codes.subscription_expiring': 'Subscription Expiring',
        'admin.templates.codes.subscription_expired': 'Subscription Expired',
        // Common extended
        'common.all': 'All',
        'common.total': 'total',
        'common.status': 'Status',
        'common.actions': 'Actions',
        'common.previous': 'Previous',
        'common.next': 'Next',
        'common.close': 'Close',
        'common.custom': 'Custom',
        'common.pause': 'Pause',
        'common.resume': 'Resume',
        'common.selectWorkspace': 'Select a workspace',
        // Heartbeats
        'heartbeats.title': 'Heartbeats',
        'heartbeats.subtitle': 'Monitor your cron jobs and background tasks',
        'heartbeats.name': 'Name',
        'heartbeats.namePlaceholder': 'Nightly Backup',
        'heartbeats.nameRequired': 'Name is required',
        'heartbeats.description': 'Description',
        'heartbeats.descriptionPlaceholder': 'Monitors the nightly database backup job',
        'heartbeats.expectedInterval': 'Expected Interval',
        'heartbeats.expectedIntervalHelp': 'How often should a ping be expected',
        'heartbeats.selectInterval': 'Select interval',
        'heartbeats.customIntervalPlaceholder': 'e.g., 2h30m',
        'heartbeats.intervalRequired': 'Expected interval is required',
        'heartbeats.gracePeriod': 'Grace Period',
        'heartbeats.gracePeriodHelp': 'Extra time before sending an alert',
        'heartbeats.selectGracePeriod': 'Select grace period',
        'heartbeats.customGracePlaceholder': 'e.g., 15m',
        'heartbeats.notifyOnLate': 'Notify when late',
        'heartbeats.notifyOnLateHelp': 'Send alert when ping is not received within expected interval + grace period',
        'heartbeats.notifyOnRecovery': 'Notify on recovery',
        'heartbeats.notifyOnRecoveryHelp': 'Send notification when heartbeat recovers from late/dead state',
        'heartbeats.create': 'Create Heartbeat',
        'heartbeats.update': 'Update Heartbeat',
        'heartbeats.created': 'Heartbeat created',
        'heartbeats.createdDescription': '"{{name}}" has been created',
        'heartbeats.updated': 'Heartbeat updated',
        'heartbeats.updatedDescription': '"{{name}}" has been updated',
        'heartbeats.failedToCreate': 'Failed to create heartbeat',
        'heartbeats.failedToUpdate': 'Failed to update heartbeat',
        'heartbeats.intervals.5m': '5 minutes',
        'heartbeats.intervals.10m': '10 minutes',
        'heartbeats.intervals.15m': '15 minutes',
        'heartbeats.intervals.30m': '30 minutes',
        'heartbeats.intervals.1h': '1 hour',
        'heartbeats.intervals.2h': '2 hours',
        'heartbeats.intervals.6h': '6 hours',
        'heartbeats.intervals.12h': '12 hours',
        'heartbeats.intervals.1d': '1 day',
        'heartbeats.interval': 'Interval',
        'heartbeats.lastPing': 'Last Ping',
        'heartbeats.grace': 'grace',
        'heartbeats.clickToCopy': 'Click to copy',
        'heartbeats.openPingUrl': 'Open ping URL',
        'heartbeats.neverPinged': 'Never pinged',
        'heartbeats.statusHealthy': 'Healthy',
        'heartbeats.statusWaiting': 'Waiting',
        'heartbeats.statusLate': 'Late',
        'heartbeats.statusDead': 'Dead',
        'heartbeats.statusPaused': 'Paused',
        'heartbeats.noHeartbeatsYet': 'No heartbeat monitors yet',
        'heartbeats.createFirstHeartbeat': 'Create your first heartbeat to start monitoring',
        'heartbeats.createHeartbeat': 'Create Heartbeat',
        'heartbeats.createDescription': 'Monitor your cron jobs and background tasks',
        'heartbeats.editHeartbeat': 'Edit Heartbeat',
        'heartbeats.editDescription': 'Update heartbeat settings',
        'heartbeats.deleteHeartbeat': 'Delete Heartbeat',
        'heartbeats.deleteConfirm': 'Are you sure you want to delete {{name}}?',
        'heartbeats.deleted': 'Heartbeat deleted',
        'heartbeats.deletedDescription': '{{name}} has been deleted',
        'heartbeats.failedToDelete': 'Failed to delete',
        'heartbeats.errorLoading': 'Error loading heartbeats',
        'heartbeats.resumed': 'Heartbeat resumed',
        'heartbeats.resumedDescription': '{{name}} has been resumed',
        'heartbeats.paused': 'Heartbeat paused',
        'heartbeats.pausedDescription': '{{name}} has been paused',
        'heartbeats.actionFailed': 'Action failed',
        'heartbeats.pingUrlCopied': 'Ping URL copied',
        'heartbeats.pingUrlCopiedDescription': 'URL copied to clipboard',
        'heartbeats.failedToCopy': 'Failed to copy',
        // Notifications
        'notifications.events': 'Notification Events',
        // SSL Monitors
        'ssl.title': 'SSL Monitors',
        'ssl.subtitle': 'Monitor SSL certificate expiration for your domains',
        'ssl.status.pending': 'Pending',
        'ssl.status.valid': 'Valid',
        'ssl.status.expiring': 'Expiring',
        'ssl.status.expired': 'Expired',
        'ssl.status.invalid': 'Invalid',
        'ssl.status.error': 'Error',
        'ssl.status.paused': 'Paused',
        'ssl.create': 'Add Monitor',
        'ssl.createMonitor': 'Add SSL Monitor',
        'ssl.createDescription': 'Add a domain to monitor its SSL certificate',
        'ssl.editMonitor': 'Edit SSL Monitor',
        'ssl.editDescription': 'Update the monitor settings',
        'ssl.deleteMonitor': 'Delete SSL Monitor',
        'ssl.deleteConfirm': 'Are you sure you want to delete "{{name}}"? This action cannot be undone.',
        'ssl.noMonitorsYet': 'No SSL monitors yet',
        'ssl.createFirstMonitor': 'Add your first SSL monitor to track certificate expiration',
        'ssl.notAvailableOnPlan': 'SSL monitoring is not available on your plan',
        'ssl.upgradeToUnlock': 'Upgrade to a plan with SSL monitoring',
        'ssl.viewPlans': 'View Plans',
        'ssl.name': 'Name',
        'ssl.namePlaceholder': 'Production API',
        'ssl.nameRequired': 'Name is required',
        'ssl.domain': 'Domain',
        'ssl.domainPlaceholder': 'example.com',
        'ssl.domainRequired': 'Domain is required',
        'ssl.domainHelp': 'Enter domain without protocol (e.g., example.com)',
        'ssl.domainCannotChange': 'Domain cannot be changed after creation',
        'ssl.port': 'Port',
        'ssl.invalidPort': 'Port must be between 1 and 65535',
        'ssl.description': 'Description',
        'ssl.descriptionPlaceholder': 'Optional description',
        'ssl.notifyOnExpiring': 'Notify when expiring',
        'ssl.notifyOnExpiringHelp': 'Send alerts at 14, 7, 3, and 1 day before certificate expiration',
        'ssl.notifyOnError': 'Notify on errors',
        'ssl.notifyOnErrorHelp': 'Send alert when SSL check fails or certificate is invalid',
        'ssl.expiryDate': 'Expiry Date',
        'ssl.lastCheck': 'Last Check',
        'ssl.neverChecked': 'Never checked',
        'ssl.checkNow': 'Check Now',
        'ssl.checkComplete': 'Check complete',
        'ssl.checkCompleteDescription': 'SSL check for "{{name}}" has been completed',
        'ssl.checkFailed': 'Check failed',
        'ssl.viewDetails': 'View details',
        'ssl.certificateDetails': 'Certificate Details',
        'ssl.daysUntilExpiry': 'Days Until Expiry',
        'ssl.days': 'days',
        'ssl.daysShort': 'd',
        'ssl.certificateInfo': 'Certificate Information',
        'ssl.issuer': 'Issuer',
        'ssl.subject': 'Subject',
        'ssl.serialNumber': 'Serial Number',
        'ssl.validFrom': 'Valid From',
        'ssl.validUntil': 'Valid Until',
        'ssl.connectionInfo': 'Connection Information',
        'ssl.tlsVersion': 'TLS Version',
        'ssl.cipherSuite': 'Cipher Suite',
        'ssl.chainValid': 'Chain Valid',
        'ssl.hostnameMatch': 'Hostname Match',
        'ssl.lastError': 'Last Error',
        'ssl.created': 'Monitor created',
        'ssl.createdDescription': '"{{name}}" has been created and checked',
        'ssl.updated': 'Monitor updated',
        'ssl.updatedDescription': '"{{name}}" has been updated',
        'ssl.failedToCreate': 'Failed to create monitor',
        'ssl.failedToUpdate': 'Failed to update monitor',
        'ssl.paused': 'Monitor paused',
        'ssl.pausedDescription': '"{{name}}" has been paused',
        'ssl.resumed': 'Monitor resumed',
        'ssl.resumedDescription': '"{{name}}" is now active',
        'ssl.deleted': 'Monitor deleted',
        'ssl.deletedDescription': '"{{name}}" has been deleted',
        'ssl.failedToDelete': 'Failed to delete monitor',
        'ssl.actionFailed': 'Action failed',
        'ssl.update': 'Update Monitor',
        'ssl.errorLoading': 'Error loading monitors',
        // Navigation
        'nav.ssl': 'SSL Monitors',
        'nav.workspaceSettings': 'Workspace',
        // Admin plans SSL
        'admin.plans.sslMonitors': 'SSL Monitors',
        'admin.plans.maxSslMonitors': 'Max SSL Monitors',
        // Workspace Settings
        'workspaceSettings.title': 'Workspace Settings',
        'workspaceSettings.description': 'Manage settings for the current workspace',
        'workspaceSettings.tabGeneral': 'General',
        'workspaceSettings.tabNotifications': 'Notifications',
        'workspaceSettings.generalInfo': 'General Information',
        'workspaceSettings.name': 'Name',
        'workspaceSettings.namePlaceholder': 'My workspace',
        'workspaceSettings.slug': 'Identifier',
        'workspaceSettings.slugDescription': 'Identifier cannot be changed after creation',
        'workspaceSettings.timezone': 'Timezone',
        'workspaceSettings.timezoneDescription': 'Timezone is used for displaying time in notifications',
        'workspaceSettings.selectTimezone': 'Select timezone',
        'workspaceSettings.noWorkspace': 'No workspace selected',
        // Notifications extended
        'notifications.events': 'Notification Events',
        'notifications.eventsDescription': 'Choose which events should trigger notifications',
        'notifications.taskFailure': 'Task Failure',
        'notifications.taskFailureDescription': 'Notify when a task fails',
        'notifications.taskRecovery': 'Task Recovery',
        'notifications.taskRecoveryDescription': 'Notify when a previously failing task succeeds',
        'notifications.taskSuccess': 'Task Success',
        'notifications.taskSuccessDescription': 'Notify on every successful task execution (can be noisy)',
        'notifications.telegram': 'Telegram',
        'notifications.telegramDescription': 'Receive notifications via Telegram bot',
        'notifications.chatIds': 'Chat IDs',
        'notifications.chatIdPlaceholder': 'Chat ID (e.g., 123456789)',
        'notifications.chatIdHint': 'Start a chat with @cronbox_bot and send /start to get your chat ID',
        'notifications.emailNotifications': 'Email',
        'notifications.emailDescription': 'Receive notifications via email',
        'notifications.emailAddresses': 'Email Addresses',
        'notifications.emailPlaceholder': 'email@example.com',
        'notifications.webhook': 'Webhook',
        'notifications.webhookDescription': 'Send notifications to a custom webhook URL',
        'notifications.webhookUrl': 'Webhook URL',
        'notifications.webhookSecret': 'Secret (optional)',
        'notifications.webhookSecretPlaceholder': 'Enter webhook secret',
        'notifications.webhookSecretHint': 'Will be sent in X-Webhook-Secret header',
        'notifications.sendTest': 'Send Test',
        'notifications.testSent': 'Test notification sent',
        'notifications.testSentDescription': 'Check your {{channel}}',
        'common.enabled': 'Enabled',
      },
    },
  },
  interpolation: {
    escapeValue: false,
  },
})

type CustomRenderOptions = Omit<RenderOptions, 'wrapper'>

// eslint-disable-next-line react-refresh/only-export-components
function AllProviders({ children }: { children: React.ReactNode }) {
  return <I18nextProvider i18n={testI18n}>{children}</I18nextProvider>
}

function customRender(ui: ReactElement, options?: CustomRenderOptions) {
  return {
    user: userEvent.setup(),
    ...render(ui, { wrapper: AllProviders, ...options }),
  }
}

// Re-export everything
// eslint-disable-next-line react-refresh/only-export-components
export * from '@testing-library/react'
export { customRender as render }
export { userEvent }
export { testI18n }
